Repository AY2122S2-CS2103T-W13-1/tp, pull requests merged in 2022-03, with the labels that each got.

#37 Edit README.md and _config.yml to match current project
  README.md
  docs/_config.yml
Labels: documentation

#67 Fix minor naming issues from person to client
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/UniqueClientList.java
  src/main/java/seedu/address/model/client/exceptions/ClientNotFoundException.java
  src/main/java/seedu/address/model/client/exceptions/DuplicateClientException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/ClientListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonAddressBookStorageTest/invalidAndValidClientAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidClientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateClientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidClientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalClientsAddressBook.json
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
  src/test/java/seedu/address/model/client/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/client/UniqueClientListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/ClientUtil.java
  src/test/java/seedu/address/testutil/EditClientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: type.Bug, severity.Low

#65 Create JsonAdaptedProcedure.java for storage
  src/main/java/seedu/address/storage/JsonAdaptedProcedure.java
Labels: type.Task, priority.High

#68 Add plan attribute to Client class
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/Plan.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/resources/view/ClientListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateClientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalClientsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/client/PlanTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/ClientUtil.java
  src/test/java/seedu/address/testutil/EditClientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: type.Task, priority.High

#79 Change testing data from individuals to company data
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/client/Name.java
  src/test/data/JsonSerializableAddressBookTest/duplicateClientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalClientsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditClientDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
  src/test/java/seedu/address/model/client/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/client/NameTest.java
  src/test/java/seedu/address/model/client/UniqueClientListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: priority.Medium

#66 Create columns for UI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProcedureCard.java
  src/main/java/seedu/address/ui/ProcedureListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ProcedureListCard.fxml
  src/main/resources/view/ProcedureListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Task, priority.High

#82 Change name of Completion variable
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/procedure/Completion.java
  src/main/java/seedu/address/model/procedure/Procedure.java
  src/main/java/seedu/address/storage/JsonAdaptedProcedure.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/testutil/ProcedureBuilder.java
Labels: severity.Low

#77 Add new command "listProc"
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ListProcCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListProcCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProcedureListPanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ListProcCommandTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/ListProcCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
Labels: type.Task, priority.High

#83 Create more Procedure Tests
  src/main/java/seedu/address/logic/commands/DeleteProcCommand.java
  src/main/java/seedu/address/logic/commands/ListProcCommand.java
  src/main/java/seedu/address/model/procedure/Completion.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/procedure/CompletionTest.java
  src/test/java/seedu/address/model/procedure/ProcedureTest.java
  src/test/java/seedu/address/testutil/ProcedureBuilder.java
  src/test/java/seedu/address/testutil/TypicalProcedures.java
Labels: type.Enhancement, priority.Medium

#84 Add AddProcCommandParser and AddProcCommand Tests
  src/main/java/seedu/address/logic/commands/AddProcCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/procedure/Cost.java
  src/main/java/seedu/address/model/procedure/Procedure.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddProcCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddProcCommandParserTest.java
  src/test/java/seedu/address/model/procedure/ProcedureTest.java
  src/test/java/seedu/address/testutil/ProcedureBuilder.java
Labels: type.Task, priority.High

#97 Update Yong Gi's part of the DG
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/ListProcCommand.puml
  docs/images/ListProcCommandExample1.PNG
  docs/images/ListProcCommandSequenceDiagram.png
  src/main/java/seedu/address/logic/LogicManager.java
Labels: documentation, priority.High

#98 Add Alexander's Portion into DG
  docs/DeveloperGuide.md
  docs/diagrams/AddProcCommand.puml
  docs/images/AddProcCommand.png
Labels: documentation, priority.High

#103 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation, priority.Medium

#102 Update Ben's part into the Developer Guide implementation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteProc.puml
  docs/diagrams/DeleteProcState0.puml
  docs/diagrams/DeleteProcState1.puml
  docs/images/DeleteProcSequenceDiagram.png
  docs/images/DeleteProcState0.png
  docs/images/DeleteProcState1.png
Labels: priority.Medium

#110 Fix documentation related issues
  docs/DeveloperGuide.md
  docs/images/ListProcCommandSequenceDiagram.png
  docs/index.md
Labels: documentation, priority.High

#114 Update DG TOC
  docs/DeveloperGuide.md
Labels: bug, documentation, priority.High, severity.Medium

#115 Fix Markdown formatting in Developer Guide
  docs/DeveloperGuide.md
Labels: bug

#112 Add implementation descriptions for ListProcOnCommand
  docs/DeveloperGuide.md
  docs/diagrams/ListProcOnCommandClassDiagram.puml
  docs/diagrams/ListProcOnCommandSequenceDiagram.puml
  docs/images/ListProcOnCommandClassDiagram.png
  docs/images/ListProcOnCommandSequenceDiagram.png
Labels: documentation, priority.High

#113 Update UG as per tP requirements
  docs/UserGuide.md
  docs/images/addClientGUI.png
  docs/images/addProcGUI.png
  docs/images/deleteClientGUI.png
  docs/images/deleteProcGUIAfter.png
  docs/images/deleteProcGUIBefore.png
  docs/images/listGUI.png
Labels: documentation, priority.High

#118 Delete Undo and Redo feature from DeveloperGuide
  docs/DeveloperGuide.md
Labels: priority.High, severity.VeryLow

#121 Add command word on listProc section
  docs/UserGuide.md
Labels: documentation, priority.Medium

#123 Format UG for better consistency
  docs/UserGuide.md
Labels: documentation, type.Bug

#85 Add Autosort Feature
  src/main/java/seedu/address/logic/commands/AddProcCommand.java
  src/main/java/seedu/address/model/procedure/Date.java
  src/test/java/seedu/address/logic/commands/AddProcCommandTest.java
  src/test/java/seedu/address/testutil/RandomProcedureBuilder.java
  src/test/java/seedu/address/testutil/TypicalRandomProcedureDetails.java
Labels: type.Enhancement, priority.High

#127 Fix images and docs in UG
  docs/UserGuide.md
  docs/images/ListProcCommandExample1.PNG
Labels: bug, documentation, enhancement

#128 edit example for listProc
  docs/UserGuide.md
Labels: documentation, priority.Medium

#134 Update HelpWindow.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: invalid, priority.High

#100 Delete Procedure tests
  src/main/java/seedu/address/logic/commands/DeleteProcCommand.java
  src/test/java/seedu/address/logic/commands/DeleteProcCommandTest.java
Labels: enhancement

#136 Fix single-worded commands from executing with arguments
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/java/seedu/address/logic/parser/ExitCommandParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ClearCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ExitCommandParserTest.java
  src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
Labels: bug, type.Bug, priority.High, severity.Medium

#99 Add MarkCommand and UnmarkCommand
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
  src/main/java/seedu/address/model/procedure/Procedure.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProcedureCard.java
  src/main/resources/view/ProcedureListCard.fxml
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
  src/test/java/seedu/address/logic/parser/ListProcCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java
  src/test/java/seedu/address/model/procedure/ProcedureTest.java
Labels: type.Task, priority.High

#139 Update Ui.png
  docs/images/Ui.png
Labels: documentation

#130 Fix UI errors and enlarge results window
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: bug, enhancement, type.Task, priority.High, severity.Medium

#138 Update UG
  docs/UserGuide.md
  docs/images/findCommandExample.png
Labels: documentation, priority.High

#145 Update user guide
  docs/UserGuide.md
  docs/images/UIGuide.png
  src/main/java/seedu/address/ui/MainWindow.java
Labels: documentation, priority.High

#125 Branch create edit proc command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddProcCommand.java
  src/main/java/seedu/address/logic/commands/EditProcCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteProcCommandParser.java
  src/main/java/seedu/address/logic/parser/EditProcCommandParser.java
  src/main/java/seedu/address/model/procedure/Procedure.java
  src/test/java/seedu/address/logic/commands/EditProcCommandTest.java
Labels: enhancement, priority.High

#141 Add testings related to ListProcOnCommand
  src/main/java/seedu/address/commons/core/datewithouttime/DateWithoutTime.java
  src/main/java/seedu/address/logic/commands/ListProcOnCommand.java
  src/main/java/seedu/address/logic/parser/ListProcOnCommandParser.java
  src/test/java/seedu/address/logic/commands/AddProcCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListProcOnCommandTest.java
  src/test/java/seedu/address/logic/parser/ListProcOnCommandParserTest.java
Labels: type.Task, priority.High
