Repository AY2122S2-CS2103T-W13-1/tp, pull requests merged in 2022-04, with the labels that each got.

#146 Update find command to display procedures correctly
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: bug, enhancement, priority.High, severity.High

#150 Add sorting date for EditProcCommand
  src/main/java/seedu/address/logic/commands/EditProcCommand.java
  src/main/java/seedu/address/logic/parser/DeleteProcCommandParser.java
Labels: bug, type.Enhancement, severity.High

#219 User guide mark unmark
  docs/UserGuide.md
Labels: bug, documentation, priority.High, severity.Medium

#220 Fix user guide bugs (table and procedure)
  docs/UserGuide.md
Labels: bug, documentation, severity.High

#232 Fix User Guide
  docs/UserGuide.md
Labels: bug, documentation

#231 Add units and labels
  src/main/java/seedu/address/ui/ProcedureCard.java
Labels: bug, type.Task, priority.High, severity.Medium

#224 Improve testing
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Task, priority.High

#223 Fix information and tag length issue for UI
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/resources/view/ProcedureListCard.fxml
Labels: bug

#215 Add more EditProcCommand tests
  src/main/java/seedu/address/logic/commands/EditProcCommand.java
  src/main/java/seedu/address/logic/parser/DeleteProcCommandParser.java
  src/main/java/seedu/address/logic/parser/EditProcCommandParser.java
  src/test/java/seedu/address/logic/commands/AddProcCommandTest.java
  src/test/java/seedu/address/logic/commands/EditProcCommandTest.java
  src/test/java/seedu/address/logic/parser/EditProcCommandParserTest.java
  src/test/java/seedu/address/testutil/EditProcedureDescriptorBuilder.java
Labels: enhancement, priority.High

#233 Update ListProc Diagram
  docs/diagrams/ListProcCommand.puml
  docs/images/ListProcCommandSequenceDiagram.png
Labels: bug, documentation

#152 Change screenshots to newer version
  docs/UserGuide.md
  docs/images/ListProcCommandExample1.PNG
  docs/images/UIGuide.png
  docs/images/addClientGUI.png
  docs/images/addProcGUI.png
  docs/images/deleteClientGUI.png
  docs/images/listGUI.png
  docs/images/listProcOn.png
Labels: documentation, priority.High

#222 Correct ClearCommand's behavior when reflecting cleared Procedures
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: bug, severity.Medium

#228 Remedy PE bugs
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteProcCommand_After.png
  docs/images/DeleteProcCommand_Before.png
  docs/images/EditClient_After.png
  docs/images/EditProcCommand_After.png
  docs/images/EditProcCommand_Before.png
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/logic/commands/EditProcCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: bug, priority.High

#237 Edit listProc and list GUI images on UG
  docs/images/ListProcCommandExample1.PNG
  docs/images/listGUI.png
Labels: bug, documentation

#236 Edit DG Use Cases and Some Details
  docs/DeveloperGuide.md
  docs/diagrams/ListProcCommand.puml
  docs/images/ListProcCommandSequenceDiagram.png
Labels: bug, documentation

#244 Update Alexander's PPP
  docs/team/aceszhenwei.md
Labels: documentation

#243 Edit Yong Gi's PPP
  docs/team/robinrojh.md
Labels: documentation

#250 Add more tests and Fix Procedure UI issue
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteProcCommand.java
  src/main/java/seedu/address/logic/commands/EditProcCommand.java
  src/test/java/seedu/address/logic/parser/DeleteProcCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditProcCommandParserTest.java
Labels: priority.Medium

#251 Edit sample data tags
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High

#252 Update UG images
  docs/UserGuide.md
  docs/images/ClearCommand_After.png
  docs/images/DeleteProcCommand_After.png
  docs/images/DeleteProcCommand_Before.png
  docs/images/EditClient_After.png
  docs/images/EditProcCommand_After.png
  docs/images/EditProcCommand_Before.png
  docs/images/ListProcCommandExample1.PNG
  docs/images/UIGuide.png
  docs/images/Ui.png
  docs/images/addClientGUI.png
  docs/images/addProcGUI.png
  docs/images/calculate.png
  docs/images/deleteClientGUI.png
  docs/images/findCommandExample.png
  docs/images/listGUI.png
  docs/images/listProcOn.png
  docs/images/mark.PNG
  docs/images/unmark.png
Labels: documentation, priority.High

#229 Add EditProcCommand into DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteProc.puml
  docs/diagrams/DeleteProcCommand.puml
  docs/diagrams/EditProcCommand.puml
  docs/images/DeleteProcSequenceDiagram.png
  docs/images/EditProcSequenceDiagram.png
Labels: documentation

#253 Update tone of speech for DG ListProc Section
  docs/DeveloperGuide.md
Labels: documentation

#246 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#255 Remove listProc example from DG
  docs/DeveloperGuide.md
Labels: bug

#261 User guide UI
  docs/images/UIGuide.png
Labels: bug, documentation

#264 Update DG diagram
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/ComponentManagers.puml
  docs/diagrams/ListProcCommand.puml
  docs/team/robinrojh.md
Labels: bug, documentation

#265 Update AddProc Sequence Diagram
  docs/diagrams/AddProcCommand.puml
  docs/images/AddProcCommand.png
Labels: documentation

#274 Update png for DG components diagram
  docs/images/ComponentManagers.png
Labels: bug, documentation

#254 Add MingHuang's part into PPP
  docs/team/teominghuang.md
Labels: documentation, priority.High, severity.VeryLow

#278 Edit Developer Guide and User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/DeleteProcCommand_After.png
  docs/images/DeleteProcCommand_Before.png
  docs/team/teominghuang.md
  preferences.json
Labels: documentation

#284 Edit DG and PPP
  docs/DeveloperGuide.md
  docs/team/robinrojh.md
Labels: bug, documentation

#283 Minor Bug Fixes + Edit Developer and User Guide.
  docs/DeleteProcGuide.md
  docs/UserGuide.md
  docs/team/iztanpy.md
  docs/team/teominghuang.md
  src/main/java/seedu/address/logic/commands/DeleteProcCommand.java
  src/main/java/seedu/address/logic/commands/EditProcCommand.java
  src/main/java/seedu/address/model/procedure/Procedure.java
  src/test/java/seedu/address/logic/commands/ListProcOnCommandTest.java
Labels: bug, documentation

#285 Update UI Guide
  docs/images/UIGuide.png
Labels: bug, documentation

#287 Update DG images
  docs/DeveloperGuide.md
  docs/images/ArchitectureSequenceDiagram.png
Labels: bug, documentation

#286 Edit User Guide
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/teominghuang.md
  src/main/java/seedu/address/logic/commands/EditProcCommand.java
Labels: documentation

#299 Edit User Guide and Model Diagram for Procedure
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteProcCommand_After.png
  docs/images/DeleteProcCommand_Before.png
  docs/images/EditProcCommand_After.png
  docs/images/EditProcCommand_Before.png
  docs/images/ModelClassDiagram.png
  docs/images/addProcGUI.png
  preferences.json
  src/main/java/seedu/address/logic/commands/DeleteProcCommand.java
  src/main/java/seedu/address/logic/commands/EditProcCommand.java
Labels: documentation

#302 Edit Developer Guide
  docs/DeveloperGuide.md
  docs/images/DeleteProcState0.png
  docs/images/DeleteProcState1.png
Labels: documentation
